<?php declare(strict_types=1);
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Ddd\Loyalty\ViewModel\CardDataProvider $cardDataProvider */
$cardDataProvider = $block->getData('view_model');
$cardNumber = $cardDataProvider->getCardNumber();
$cardIsNotRegistered = empty($cardNumber);
$buttonLabel = $cardIsNotRegistered ? __('Save') : __('Delete');
$buttonTitle = $cardIsNotRegistered ? __('Save new card') : __('Delete existing card');
$postUrl = $cardIsNotRegistered ? 'loyalty/card/save' : 'loyalty/card/delete';
?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl($postUrl)) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">

    <fieldset class="fieldset card">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field">
            <label for="card-number" class="label">
                <span><?= $block->escapeHtml(__('Your card number')) ?></span>
            </label>
            <div class="control">
                <?php if ($cardIsNotRegistered): ?>
                <input type="text"
                       name="card_number"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Card Number')) ?>"
                       id="card-number"
                       class="input-text" />
                <?php else: ?>
                    <strong><?= $cardNumber ?></strong>
                <?php endif; ?>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit"
                        class="action submit primary"
                        title="<?= $block->escapeHtml($buttonTitle) ?>">
                    <span><?= $block->escapeHtml($buttonLabel) ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>
